/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_oracle_appbundler_runtime_ICloudDrive */

#ifndef _Included_com_oracle_appbundler_runtime_ICloudDrive
#define _Included_com_oracle_appbundler_runtime_ICloudDrive
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_oracle_appbundler_runtime_ICloudDrive
 * Method:    jni_getPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_oracle_appbundler_runtime_ICloudDrive_jni_1getPath
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
